export const ADD_TO_CART ='ADD_TO_CART';
export const CHANGE_MESSAGE='CHANG_MESSAGE';
export const DELETE_PRODUCT_IN_CART ='DELETE_PRODUCT_IN_CART';
export const UP_DATE_PRODUCT_IN_CART = 'UP_DATE_PRODUCT_IN_CART';